

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/layouts/Header";
import SmoothScroll from "../components/scroll/SmoothScroll";
import Footer from "../components/layouts/Footer";
import AnimatedCursor from "react-animated-cursor";
import { ModalProvider } from "@/components/context/ModalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
   
     
      <html lang="en">
      <body className={inter.className}>
      <AnimatedCursor
            innerSize={20}
            outerSize={13}
            color="218,165,32" // لون ذهبي أغمق
            outerAlpha={0.2}
            innerScale={0.7}
            outerScale={8}
            innerStyle={{
              backgroundColor: " #c59c6e",
            }}
            clickables={[
              "a",
              'input[type="text"]',
              'input[type="email"]',
              'input[type="number"]',
              'input[type="submit"]',
              'input[type="image"]',
              "label[for]",
              "select",
              "textarea",
              "button",
              ".link",
            ]}
          />
    
             <SmoothScroll>
             <main>
                
             
                {children}
                
               
                </ main>
             </SmoothScroll>
             
           
            
        
         
      </body>
      </html>
         
        
     
  );
}
